# Generated by Django 3.2.8 on 2021-10-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questtion_text',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='time_pub',
            new_name='time_date',
        ),
    ]
